name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to 'main' branch



jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout the repository 
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'  # Ensure it matches your local Ruby version

      - name: Install dependencies
        run: |
          gem install bundler  # Install Bundler if not already installed
          bundle install        # Install your gems using Bundler

      - name: Build the site
        run: |
          bundle exec jekyll build  # Build the site with Jekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Location of the generated static site
          publish_branch: gh-pages  # Deploy to the 'main' branch
